from django.urls import path, include  # Import utilities for defining URL patterns and including other URL configurations
from rest_framework.routers import DefaultRouter  # Import the DRF DefaultRouter for automatically generating routes
from .views import BookViewSet  # Import the viewset that handles operations for the "books" resource

# Initialize a DefaultRouter instance
router = DefaultRouter()  
# Register the 'books' endpoint with the BookViewSet
# - The URL pattern will be: /books/ (list and create)
# - The URL pattern will also include: /books/<pk>/ (retrieve, update, delete)
router.register(r'books', BookViewSet)

# Define URL patterns for this app
urlpatterns = [
    # Include the routes generated by the router
    # This dynamically adds all the CRUD routes for the 'books' resource
    path('', include(router.urls)),  
]
